spring.application.name=Spring Security


#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=system
#spring.datasource.password=system
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


# ==============================
# ✅ RENDER POSTGRESQL CONFIG
# ==============================

spring.datasource.url=jdbc:postgresql://dpg-d75a2f7pm1nc739c8jbg-a.oregon-postgres.render.com:5432/bmp_dev_v3?sslmode=require
spring.datasource.username=bmp_dev_v3_user
spring.datasource.password=W7I2GlQ51UoLOmVXIlgEm3lBtkpHzPgY
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# ✅ JPA CONFIG
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# VERY IMPORTANT
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# ✅ HIKARI (TUNED FOR CLOUD DB)
# ==============================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=30000

# Prevent metadata issues
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true

# ==============================
# ✅ SERVER
# ==============================

server.port=8080

# ==============================
# ✅ FILE UPLOAD
# ==============================

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# ==============================
# ✅ ERROR HANDLING
# ==============================

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring.mvc.error.whitelabel.enabled=false

# ==============================
# ✅ JWT
# ==============================

jwt.secret='[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
jwt.expiration=86400000


#------------------------
#   Email
#----------------------

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.from=${MAIL_FROM:javadeveloper.ja@gmail.com}